class 18 done
Fullstack-Alfanar/yosef-a-resume pull request #4
Opened 2022-04-10 22:37 UTC by yosef406

class 18 is done
with some dom styling

2022-04-10 22:37 UTC, yosef406 commented
fixed the conflict in readme.md

2022-04-11 14:45 UTC, EliasSalom requested changes
please check this

2022-04-11 14:45 UTC, EliasSalom commented on script/script.js
> +    let invalidDataText = document.querySelector("h4");
test

2022-04-11 14:46 UTC, yosef406 commented on script/script.js
> +    let invalidDataText = document.querySelector("h4");
resolved

2022-04-16 19:23 UTC, yosef406 commented
closing because its past do.

2022-04-16 19:23 UTC, closed without merging